/* Generated By:JavaCC: Do not edit this line. GuruCParser.java */
package com.guru.language;
import java.util.*;
import com.guru.generator.*;

  public class GuruCParser implements GuruCParserConstants {
        private static Classes classes = new Classes();

    // Hastable for storing typedef types
    private static Set types = new HashSet();

    // Stack for determining when the parser 
    // is parsing a typdef definition.
    private static Stack typedefParsingStack = new Stack();

    // Returns true if the given string is
    // a typedef type.
    private static boolean isType(String type){
          return types.contains(type);
    }

    // Add a typedef type to those already defined
    private static void addType(String type){
          types.add(type);
    }

    // Prints out all the types used in parsing the c source
    private static void printTypes(){
      for (Iterator i = types.iterator(); i.hasNext();) {
        System.out.println(i.next());
      }
    }

    // Run the parser
    public static void main ( String args [ ] ) {
      GuruCParser parser = null;

          // Hack to include type "special types"
            types.add("__signed__");
            types.add("__const");
            types.add("__inline__");
            types.add("__signed");

      if(args.length == 0){
        System.out.println("Guru Parser .1:  Reading from standard input . . .");
        parser = new GuruCParser(System.in);
      }
      else if(args.length == 1){
        System.out.println("Guru Parser .1:  Reading from file " + args[0] + " . . ." );
      try {
        if(parser!= null && parser.jj_initialized_once)
        {
          parser.ReInit(new java.io.FileInputStream(args[0]));
        }else
        {

                parser = new GuruCParser(new java.io.FileInputStream(args[0]));
      }
      }
      catch(java.io.FileNotFoundException e){
        System.out.println("C Parser Version 0.1:  File " + args[0] + " not found.");
        return ;
        }
      }
      else {
        System.out.println("Guru Parser .1:  Usage is one of:");
        System.out.println("         java CParser < inputfile");
        System.out.println("OR");
        System.out.println("         java CParser inputfile");
        return ;
      }
      try {
        parser.TranslationUnit();
        //System.out.println("Guru Parser .1:  Java program parsed successfully.");
        classes.build();
      }
      catch(ParseException e){
        System.out.println("Guru Parser .1:  Encountered errors during parse.");
        e.printStackTrace();
      }
    }

  static final public void TranslationUnit() throws ParseException {
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case EXTENDS:
      case IDENTIFIER:
      case 61:
        ;
        break;
      default:
        jj_la1[0] = jj_gen;
        break label_1;
      }
      ClassDeclaration();
    }
  }

  static final public void ClassDeclaration() throws ParseException {
                           Token t;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case IDENTIFIER:
      t = jj_consume_token(IDENTIFIER);
          classes.addClass(t.toString());
      break;
    default:
      jj_la1[1] = jj_gen;
      ;
    }
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case EXTENDS:
      jj_consume_token(EXTENDS);
      jj_consume_token(IDENTIFIER);
      label_2:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case 60:
          ;
          break;
        default:
          jj_la1[2] = jj_gen;
          break label_2;
        }
        jj_consume_token(60);
        jj_consume_token(IDENTIFIER);
      }
      break;
    default:
      jj_la1[3] = jj_gen;
      ;
    }
    ClassMembers();
  }

  static final public void ClassMembers() throws ParseException {
    jj_consume_token(61);
    label_3:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case IDENTIFIER:
      case 63:
        ;
        break;
      default:
        jj_la1[4] = jj_gen;
        break label_3;
      }
      MemberDeclaration();
    }
    jj_consume_token(62);
  }

  static final public void MemberDeclaration() throws ParseException {
                            String s;
    if (jj_2_1(2147483647)) {
      attributos();
    } else {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case IDENTIFIER:
        metodos();
        break;
      case 63:
        construtores();
        break;
      default:
        jj_la1[5] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
  }

  static final public void construtores() throws ParseException {
                     String params;
    if (jj_2_2(2)) {
      jj_consume_token(63);
      jj_consume_token(64);
    classes.get().addConstructor();
      CompoundStatement();
    } else {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 63:
        jj_consume_token(63);
        params = Parametros();
        jj_consume_token(64);
    classes.get().addConstructor(params);
        CompoundStatement();
        break;
      default:
        jj_la1[6] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
  }

  static final public void metodos() throws ParseException {
    if (jj_2_3(2147483647)) {
      metodos_com_parametros();
    } else {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case IDENTIFIER:
        metodos_sem_parametros();
        break;
      default:
        jj_la1[7] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
  }

  static final public void metodos_com_parametros() throws ParseException {
                               Token t,t2;String params,s;
    if (jj_2_4(2)) {
      t = jj_consume_token(IDENTIFIER);
      jj_consume_token(63);
      params = Parametros();
      jj_consume_token(64);
        classes.get().addMethodWithParams(t.toString(), params);
      s = CompoundStatement();
    } else {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case IDENTIFIER:
        t = jj_consume_token(IDENTIFIER);
        t2 = jj_consume_token(IDENTIFIER);
        jj_consume_token(63);
        params = Parametros();
        jj_consume_token(64);
  classes.get().addMethod(t2.toString(),params,t.toString());
        s = CompoundStatement();
        break;
      default:
        jj_la1[8] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
  classes.get().addStatement(s);
  }

  static final public void metodos_sem_parametros() throws ParseException {
                               Token t,t2;String s;
    if (jj_2_5(2)) {
      t = jj_consume_token(IDENTIFIER);
  classes.get().addMethod(t.toString());
      s = CompoundStatement();
  classes.get().addStatement(s);
    } else {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case IDENTIFIER:
        t = jj_consume_token(IDENTIFIER);
        t2 = jj_consume_token(IDENTIFIER);
  classes.get().addMethodWithReturn(t2.toString(),t.toString());
        s = CompoundStatement();
  classes.get().addStatement(s);
        break;
      default:
        jj_la1[9] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
  }

  static final public String CompoundStatement() throws ParseException {
                              String retorno="",s;
    jj_consume_token(61);
    label_4:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case INTEGER_LITERAL:
      case FLOATING_POINT_LITERAL:
      case SWITCH:
      case WHILE:
      case IF:
      case FOR:
      case DO:
      case IDENTIFIER:
      case 63:
      case 84:
      case 96:
      case 97:
      case 101:
      case 102:
      case 103:
      case 104:
      case 108:
        ;
        break;
      default:
        jj_la1[10] = jj_gen;
        break label_4;
      }
      s = Statement();
                        retorno += s;
    }
    jj_consume_token(62);
          {if (true) return retorno;}
    throw new Error("Missing return statement in function");
  }

  static final public String Statement() throws ParseException {
                      String retorno = "",tmp;
    if (jj_2_7(2)) {
      retorno = Expression();
      jj_consume_token(65);
          retorno += ";\u005cn";
    } else if (jj_2_8(2)) {
      Variable();
      Variable();
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 66:
        jj_consume_token(66);
        Expression();
        break;
      default:
        jj_la1[11] = jj_gen;
        ;
      }
      label_5:
      while (true) {
        if (jj_2_6(2)) {
          ;
        } else {
          break label_5;
        }
        jj_consume_token(60);
        Variable();
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case 66:
          jj_consume_token(66);
          Expression();
          break;
        default:
          jj_la1[12] = jj_gen;
          ;
        }
      }
      jj_consume_token(65);
    } else {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case IDENTIFIER:
        retorno = Variable();
        jj_consume_token(66);
          retorno += " = ";
        tmp = Expression();
          retorno += tmp +";";
        jj_consume_token(65);
        break;
      case SWITCH:
      case IF:
        retorno = SelectionStatement();
        break;
      case WHILE:
      case FOR:
      case DO:
        retorno = IterationStatement();
        break;
      default:
        jj_la1[13] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
  {if (true) return retorno;}
    throw new Error("Missing return statement in function");
  }

  static final public String SelectionStatement() throws ParseException {
                               Token t;String retorno="",s="",exp="";
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case IF:
      t = jj_consume_token(IF);
      jj_consume_token(63);
      exp = Expression();
      jj_consume_token(64);
      s = CompoundStatement();
                  retorno = t.toString() + "("+exp+")"+ "{\u005cn"+s+"\u005cn}";
      label_6:
      while (true) {
        if (jj_2_9(2)) {
          ;
        } else {
          break label_6;
        }
        t = jj_consume_token(ELSEIF);
        jj_consume_token(63);
        exp = Expression();
        jj_consume_token(64);
        s = CompoundStatement();
                  retorno += t.toString() + "("+exp+")"+ "{\u005cn"+s+"\u005cn}";
      }
      if (jj_2_10(2)) {
        t = jj_consume_token(ELSE);
        s = CompoundStatement();
                                retorno += t.toString() + "{\u005cn"+s+"\u005cn}";
      } else {
        ;
      }
      break;
    case SWITCH:
      t = jj_consume_token(SWITCH);
      jj_consume_token(63);
      exp = Expression();
      jj_consume_token(64);
      s = CompoundStatement();
                  retorno = t.toString() + "("+"){"+s+"}";
      break;
    default:
      jj_la1[14] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
          {if (true) return retorno;}
    throw new Error("Missing return statement in function");
  }

  static final public String IterationStatement() throws ParseException {
                               String retorno="",s="",exp="",tmp="";
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case WHILE:
      jj_consume_token(WHILE);
      jj_consume_token(63);
      exp = Expression();
      jj_consume_token(64);
      tmp = CompoundStatement();
            retorno = "while ( %exp% ){ %statments% }".replace("%exp%",exp).replace("%statments%",tmp);
      break;
    case DO:
      jj_consume_token(DO);
      tmp = CompoundStatement();
      jj_consume_token(WHILE);
      jj_consume_token(63);
      exp = Expression();
      jj_consume_token(64);
      EndOfStatement();
            retorno = " do{ %statments% }while( %exp% );".replace("%exp%",exp).replace("%statments%",tmp);
      break;
    case FOR:
      jj_consume_token(FOR);
      jj_consume_token(63);
      Expression();
      jj_consume_token(65);
      Expression();
      jj_consume_token(65);
      Expression();
      jj_consume_token(64);
      CompoundStatement();
      break;
    default:
      jj_la1[15] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
            {if (true) return retorno;}
    throw new Error("Missing return statement in function");
  }

  static final public void EndOfStatement() throws ParseException {
    jj_consume_token(65);
  }

  static final public String Expression() throws ParseException {
                       String retorno;
    retorno = LogicalTextOrExpression();
           {if (true) return retorno.trim();}
    throw new Error("Missing return statement in function");
  }

  static final public String LogicalTextOrExpression() throws ParseException {
                                   String tmp1="",tmp2="",tmp3="";Token t= null;
    tmp1 = LogicalTextXorExpression();
    if (jj_2_11(2)) {
      t = jj_consume_token(OR);
      tmp3 = LogicalTextOrExpression();
                                                                                               tmp2= t.toString();
    } else {
      ;
    }
      {if (true) return "%exp1% %con% %exp2%".replace("%exp1%",tmp1).replace("%con%",tmp2).replace("%exp2%",tmp3).trim();}
    throw new Error("Missing return statement in function");
  }

  static final public String LogicalTextXorExpression() throws ParseException {
                                     String tmp1="",tmp2="",tmp3="";Token t= null;
    tmp1 = LogicalTextAndExpression();
    if (jj_2_12(2)) {
      t = jj_consume_token(XOR);
      tmp3 = LogicalTextXorExpression();
                                                                                                  tmp2= t.toString();
    } else {
      ;
    }
      {if (true) return "%exp1% %con% %exp2%".replace("%exp1%",tmp1).replace("%con%",tmp2).replace("%exp2%",tmp3).trim();}
    throw new Error("Missing return statement in function");
  }

  static final public String LogicalTextAndExpression() throws ParseException {
                                     String tmp1="",tmp2="",tmp3="";Token t= null;
    tmp1 = AssignmentExpression();
    if (jj_2_13(2)) {
      t = jj_consume_token(AND);
      LogicalTextAndExpression();
                                                                                        tmp2= t.toString();
    } else {
      ;
    }
      {if (true) return "%exp1% %con% %exp2%".replace("%exp1%",tmp1).replace("%con%",tmp2).replace("%exp2%",tmp3).trim();}
    throw new Error("Missing return statement in function");
  }

  static final public String AssignmentExpression() throws ParseException {
                                 String tmp1="",tmp2="",tmp3="";Token t= null;
    tmp1 = ConditionalExpression();
    if (jj_2_14(2)) {
      tmp2 = AssignmentOperator();
      tmp3 = Expression();
    } else {
      ;
    }
      {if (true) return "%exp1% %exp2% %exp3%".replace("%exp1%",tmp1).replace("%exp2%",tmp2).replace("%exp3%",tmp3).trim();}
    throw new Error("Missing return statement in function");
  }

  static final public String AssignmentOperator() throws ParseException {
                               Token r;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 66:
      r = jj_consume_token(66);
      break;
    case 67:
      r = jj_consume_token(67);
      break;
    case 68:
      r = jj_consume_token(68);
      break;
    case 69:
      r = jj_consume_token(69);
      break;
    case 70:
      r = jj_consume_token(70);
      break;
    case 71:
      r = jj_consume_token(71);
      break;
    case 72:
      r = jj_consume_token(72);
      break;
    case 73:
      r = jj_consume_token(73);
      break;
    case 74:
      r = jj_consume_token(74);
      break;
    case 75:
      r = jj_consume_token(75);
      break;
    case 76:
      r = jj_consume_token(76);
      break;
    case 77:
      r = jj_consume_token(77);
      break;
    default:
      jj_la1[16] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
      {if (true) return r.toString();}
    throw new Error("Missing return statement in function");
  }

  static final public String ConditionalExpression() throws ParseException {
                                  String tmp1="",tmp2="",tmp3="";Token t= null;
    tmp1 = Logical_Or_Expression();
    if (jj_2_15(2)) {
      t = jj_consume_token(78);
      tmp2 = Expression();
      jj_consume_token(79);
      tmp3 = Expression();
    } else {
      ;
    }
        if (t!=null)
            {if (true) return "%exp1% %token% %exp2% : %exp3%".replace("%exp1%",tmp1).replace("%token%",t!=null?t.toString():"").replace("%exp2%",tmp2).replace("%exp3%",tmp3).trim();}
        else
            {if (true) return "%exp1%".replace("%exp1%",tmp1).trim();}
    throw new Error("Missing return statement in function");
  }

  static final public String Logical_Or_Expression() throws ParseException {
                                  String tmp1="",tmp3="";Token tmp2=null;
    tmp1 = Logical_And_Expression();
    if (jj_2_16(2)) {
      tmp2 = jj_consume_token(80);
      tmp3 = Logical_Or_Expression();
    } else {
      ;
    }
      {if (true) return "%exp1% %exp2% %exp3%".replace("%exp1%",tmp1).replace("%exp2%",tmp2!=null?tmp2.toString():"").replace("%exp3%",tmp3).trim();}
    throw new Error("Missing return statement in function");
  }

  static final public String Logical_And_Expression() throws ParseException {
                                   String tmp1="",tmp3="";Token tmp2=null;
    tmp1 = BitwiseOrExpression();
    if (jj_2_17(2)) {
      tmp2 = jj_consume_token(81);
      tmp3 = Logical_And_Expression();
    } else {
      ;
    }
      {if (true) return "%exp1% %exp2% %exp3%".replace("%exp1%",tmp1).replace("%exp2%",tmp2!=null?tmp2.toString():"").replace("%exp3%",tmp3).trim();}
    throw new Error("Missing return statement in function");
  }

  static final public String BitwiseOrExpression() throws ParseException {
                                 String tmp1="",tmp3="";Token tmp2=null;
    tmp1 = BitwiseXorExpression();
    if (jj_2_18(2)) {
      tmp2 = jj_consume_token(82);
      tmp3 = BitwiseOrExpression();
    } else {
      ;
    }
      {if (true) return "%exp1% %exp2% %exp3%".replace("%exp1%",tmp1).replace("%exp2%",tmp2!=null?tmp2.toString():"").replace("%exp3%",tmp3).trim();}
    throw new Error("Missing return statement in function");
  }

  static final public String BitwiseXorExpression() throws ParseException {
                                 String tmp1="",tmp3="";Token tmp2=null;
    tmp1 = BitwiseAndExpression();
    if (jj_2_19(2)) {
      tmp2 = jj_consume_token(83);
      tmp3 = BitwiseXorExpression();
    } else {
      ;
    }
      {if (true) return "%exp1% %exp2% %exp3%".replace("%exp1%",tmp1).replace("%exp2%",tmp2!=null?tmp2.toString():"").replace("%exp3%",tmp3).trim();}
    throw new Error("Missing return statement in function");
  }

  static final public String BitwiseAndExpression() throws ParseException {
                                 String tmp1="",tmp3="";Token tmp2=null;
    tmp1 = EqualityExpression();
    if (jj_2_20(2)) {
      tmp2 = jj_consume_token(84);
      tmp3 = BitwiseAndExpression();
    } else {
      ;
    }
      {if (true) return "%exp1% %exp2% %exp3%".replace("%exp1%",tmp1).replace("%exp2%",tmp2!=null?tmp2.toString():"").replace("%exp3%",tmp3).trim();}
    throw new Error("Missing return statement in function");
  }

  static final public String EqualityExpression() throws ParseException {
                               String tmp1="",tmp3="";Token tmp2=null;
    tmp1 = RelationalExpression();
    if (jj_2_21(2)) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 85:
        tmp2 = jj_consume_token(85);
        break;
      case 86:
        tmp2 = jj_consume_token(86);
        break;
      case 87:
        tmp2 = jj_consume_token(87);
        break;
      case 88:
        tmp2 = jj_consume_token(88);
        break;
      default:
        jj_la1[17] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      tmp3 = EqualityExpression();
    } else {
      ;
    }
      {if (true) return "%exp1% %exp2% %exp3%".replace("%exp1%",tmp1).replace("%exp2%",tmp2!=null?tmp2.toString():"").replace("%exp3%",tmp3).trim();}
    throw new Error("Missing return statement in function");
  }

  static final public String RelationalExpression() throws ParseException {
                                 String tmp1="",tmp3="";Token tmp2=null;
    tmp1 = ShiftExpression();
    if (jj_2_22(2)) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 89:
        tmp2 = jj_consume_token(89);
        break;
      case 90:
        tmp2 = jj_consume_token(90);
        break;
      case 91:
        tmp2 = jj_consume_token(91);
        break;
      case 92:
        tmp2 = jj_consume_token(92);
        break;
      default:
        jj_la1[18] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      tmp3 = RelationalExpression();
    } else {
      ;
    }
      {if (true) return "%exp1% %exp2% %exp3%".replace("%exp1%",tmp1).replace("%exp2%",tmp2!=null?tmp2.toString():"").replace("%exp3%",tmp3).trim();}
    throw new Error("Missing return statement in function");
  }

  static final public String ShiftExpression() throws ParseException {
                            String tmp1="",tmp3="";Token tmp2=null;
    tmp1 = AdditiveExpression();
    if (jj_2_23(2)) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 93:
        tmp2 = jj_consume_token(93);
        break;
      case 94:
        tmp2 = jj_consume_token(94);
        break;
      default:
        jj_la1[19] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      tmp3 = ShiftExpression();
    } else {
      ;
    }
      {if (true) return "%exp1% %exp2% %exp3%".replace("%exp1%",tmp1).replace("%exp2%",tmp2!=null?tmp2.toString():"").replace("%exp3%",tmp3).trim();}
    throw new Error("Missing return statement in function");
  }

  static final public String AdditiveExpression() throws ParseException {
                               String tmp1="",tmp3="";Token tmp2=null;
    tmp1 = MultiplicativeExpression();
    if (jj_2_24(2)) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 95:
        tmp2 = jj_consume_token(95);
        break;
      case 96:
        tmp2 = jj_consume_token(96);
        break;
      case 97:
        tmp2 = jj_consume_token(97);
        break;
      default:
        jj_la1[20] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      tmp3 = AdditiveExpression();
    } else {
      ;
    }
      {if (true) return "%exp1% %exp2% %exp3%".replace("%exp1%",tmp1).replace("%exp2%",tmp2!=null?tmp2.toString():"").replace("%exp3%",tmp3).trim();}
    throw new Error("Missing return statement in function");
  }

  static final public String MultiplicativeExpression() throws ParseException {
                                     String tmp1="",tmp3="";Token tmp2=null;
    tmp1 = CastExpression();
    if (jj_2_25(2)) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 98:
        tmp2 = jj_consume_token(98);
        break;
      case 99:
        tmp2 = jj_consume_token(99);
        break;
      case 100:
        tmp2 = jj_consume_token(100);
        break;
      default:
        jj_la1[21] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      tmp3 = MultiplicativeExpression();
    } else {
      ;
    }
      {if (true) return "%exp1% %exp2% %exp3%".replace("%exp1%",tmp1).replace("%exp2%",tmp2!=null?tmp2.toString():"").replace("%exp3%",tmp3).trim();}
    throw new Error("Missing return statement in function");
  }

  static final public String CastExpression() throws ParseException {
                           Token t1=null, t2=null; String tmp1="";
    if (jj_2_26(2147483647)) {
      jj_consume_token(63);
      t2 = jj_consume_token(IDENTIFIER);
      jj_consume_token(64);
    } else {
      ;
    }
    tmp1 = UnaryExpression();
        if(t1==null)
        {if (true) return "%exp3%".replace("%exp3%",tmp1).trim();}
        else
        {if (true) return "(%exp1%) (%exp2%) %exp3%".replace("%exp1%",t1!=null?t1.toString():"").replace("%exp2%",t2!=null?t2.toString():"").replace("%exp3%",tmp1).trim();}
    throw new Error("Missing return statement in function");
  }

  static final public String UnaryExpression() throws ParseException {
                            Token t1, t2; String tmp1="",tmp2;
    label_7:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 84:
      case 96:
      case 101:
      case 102:
        ;
        break;
      default:
        jj_la1[22] = jj_gen;
        break label_7;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 84:
        t1 = jj_consume_token(84);
        break;
      case 96:
        t1 = jj_consume_token(96);
        break;
      case 101:
        t1 = jj_consume_token(101);
        break;
      case 102:
        t1 = jj_consume_token(102);
        break;
      default:
        jj_la1[23] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
                                                  tmp1+=t1.toString();
    }
    tmp2 = PrefixIncDecExpression();
      {if (true) return "%exp1% %exp2%".replace("%exp1%",tmp1.toString()).replace("%exp2%",tmp2).trim();}
    throw new Error("Missing return statement in function");
  }

  static final public String PrefixIncDecExpression() throws ParseException {
                                   Token t1;String tmp1 = "", tmp2="";
    label_8:
    while (true) {
      if (jj_2_27(3)) {
        ;
      } else {
        break label_8;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 103:
        t1 = jj_consume_token(103);
        break;
      case 104:
        t1 = jj_consume_token(104);
        break;
      default:
        jj_la1[24] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
                                           tmp1+=t1.toString();
    }
    tmp2 = PostfixIncDecExpression();
      {if (true) return "%exp1% %exp2%".replace("%exp1%",tmp1).replace("%exp2%",tmp2).trim();}
    throw new Error("Missing return statement in function");
  }

  static final public String PostfixIncDecExpression() throws ParseException {
                                    String tmp1,tmp="";Token tmp2;
    tmp1 = InstanceOfExpression();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 103:
    case 104:
      label_9:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case 103:
          tmp2 = jj_consume_token(103);
          break;
        case 104:
          tmp2 = jj_consume_token(104);
          break;
        default:
          jj_la1[25] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
                                                                                tmp+=tmp2.toString();
        if (jj_2_28(3)) {
          ;
        } else {
          break label_9;
        }
      }
      break;
    default:
      jj_la1[26] = jj_gen;
      ;
    }
      {if (true) return "%exp1% %exp2%".replace("%exp1%",tmp1).replace("%exp2%",tmp).trim();}
    throw new Error("Missing return statement in function");
  }

  static final public String InstanceOfExpression() throws ParseException {
                                 String tmp1,tmp2="";Token t=null;
    tmp1 = PostfixExpression();
    if (jj_2_29(2)) {
      t = jj_consume_token(INSTANCEOF);
      tmp2 = Expression();
    } else {
      ;
    }
      {if (true) return "%exp1% %exp2% %exp3%".replace("%exp1%",tmp1).replace("%exp2%",t!=null?t.toString():"").replace("%exp3%",tmp2).trim();}
    throw new Error("Missing return statement in function");
  }

  static final public String PostfixExpression() throws ParseException {
                              String tmp1,tmp2="",tmp3=null, tmp4;Token t;
    tmp1 = PrimaryExpression();
    label_10:
    while (true) {
      if (jj_2_30(3)) {
        ;
      } else {
        break label_10;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 63:
        jj_consume_token(63);
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case INTEGER_LITERAL:
        case FLOATING_POINT_LITERAL:
        case IDENTIFIER:
        case 97:
        case 108:
          tmp3 = Argumentos();
          break;
        default:
          jj_la1[27] = jj_gen;
          ;
        }
        jj_consume_token(64);
                                           tmp4="(%r%)";
        break;
      case 97:
        jj_consume_token(97);
        tmp3 = PostfixExpression();
                                           tmp4=".%r%";
        break;
      case 105:
        jj_consume_token(105);
        tmp3 = PostfixExpression();
                                            tmp4="::%r%";
        break;
      case 106:
        jj_consume_token(106);
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case INTEGER_LITERAL:
        case FLOATING_POINT_LITERAL:
        case IDENTIFIER:
        case 63:
        case 84:
        case 96:
        case 97:
        case 101:
        case 102:
        case 103:
        case 104:
        case 108:
          tmp3 = Expression();
          break;
        default:
          jj_la1[28] = jj_gen;
          ;
        }
        jj_consume_token(107);
                                           tmp4="[%r%]";
        break;
      case 61:
        jj_consume_token(61);
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case INTEGER_LITERAL:
        case FLOATING_POINT_LITERAL:
        case IDENTIFIER:
        case 63:
        case 84:
        case 96:
        case 97:
        case 101:
        case 102:
        case 103:
        case 104:
        case 108:
          tmp3 = Expression();
          break;
        default:
          jj_la1[29] = jj_gen;
          ;
        }
        jj_consume_token(62);
                                           tmp4="{%r%}";
        break;
      default:
        jj_la1[30] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
                if(tmp3!=null){
                    tmp2+=tmp4.replace("%r%",tmp3);
                    tmp3=null;
                }
    }
  {if (true) return "%exp1% %exp2%".replace("%exp1%",tmp1).replace("%exp2%",tmp2).trim();}
    throw new Error("Missing return statement in function");
  }

  static final public String PrimaryExpression() throws ParseException {
                              String tmp;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case INTEGER_LITERAL:
    case FLOATING_POINT_LITERAL:
    case IDENTIFIER:
    case 97:
    case 108:
      tmp = Constant();
      break;
    case 63:
      jj_consume_token(63);
      tmp = Expression();
      jj_consume_token(64);
                              tmp = "("+tmp+")";
      break;
    default:
      jj_la1[31] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
 {if (true) return tmp.trim();}
    throw new Error("Missing return statement in function");
  }

  static final public String Constant() throws ParseException {
                     Token t,t2 = null;String retorno="";
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case INTEGER_LITERAL:
      t = jj_consume_token(INTEGER_LITERAL);
                                retorno = t.toString();
      break;
    case FLOATING_POINT_LITERAL:
      t = jj_consume_token(FLOATING_POINT_LITERAL);
                                                                                        retorno = t.toString();
      break;
    case 108:
      retorno = String();
      break;
    case IDENTIFIER:
    case 97:
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 97:
        t2 = jj_consume_token(97);
        break;
      default:
        jj_la1[32] = jj_gen;
        ;
      }
      t = jj_consume_token(IDENTIFIER);
                                                                                                                                                                  retorno =(t2!=null?"this->":"")+t.toString();
      break;
    default:
      jj_la1[33] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
         {if (true) return retorno.trim();}
    throw new Error("Missing return statement in function");
  }

  static final public String String() throws ParseException {
    jj_consume_token(108);
    jj_consume_token(108);
 {if (true) return "TEXTO";}
    throw new Error("Missing return statement in function");
  }

  static final public String Variable() throws ParseException {
                     Token t;
    t = jj_consume_token(IDENTIFIER);
          {if (true) return t.toString();}
    throw new Error("Missing return statement in function");
  }

  static final public String Argumentos() throws ParseException {
                       String tmp="", tmp2;
    tmp = Constant();
    label_11:
    while (true) {
      if (jj_2_31(2)) {
        ;
      } else {
        break label_11;
      }
      jj_consume_token(60);
      tmp2 = Constant();
                                                         tmp+= ", "+tmp2;
    }
     {if (true) return tmp;}
    throw new Error("Missing return statement in function");
  }

  static final public String Parametros() throws ParseException {
                       String retorno, tmp;
    retorno = Parametro();
    label_12:
    while (true) {
      if (jj_2_32(2)) {
        ;
      } else {
        break label_12;
      }
      jj_consume_token(60);
      tmp = Parametros();
          retorno += ", " + tmp;
    }
          {if (true) return retorno;}
    throw new Error("Missing return statement in function");
  }

  static final public String Parametro() throws ParseException {
                      Token t;String retorno;
    t = jj_consume_token(IDENTIFIER);
          retorno = t.toString();
    t = jj_consume_token(IDENTIFIER);
          retorno += " "+t.toString();
          {if (true) return retorno;}
    throw new Error("Missing return statement in function");
  }

  static final public void attributos() throws ParseException {
    jj_consume_token(IDENTIFIER);
    jj_consume_token(IDENTIFIER);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case INTEGER_LITERAL:
    case FLOATING_POINT_LITERAL:
    case IDENTIFIER:
    case 63:
    case 84:
    case 96:
    case 97:
    case 101:
    case 102:
    case 103:
    case 104:
    case 108:
      Expression();
      break;
    default:
      jj_la1[34] = jj_gen;
      ;
    }
    label_13:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 60:
        ;
        break;
      default:
        jj_la1[35] = jj_gen;
        break label_13;
      }
      jj_consume_token(60);
      jj_consume_token(IDENTIFIER);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case INTEGER_LITERAL:
      case FLOATING_POINT_LITERAL:
      case IDENTIFIER:
      case 63:
      case 84:
      case 96:
      case 97:
      case 101:
      case 102:
      case 103:
      case 104:
      case 108:
        Expression();
        break;
      default:
        jj_la1[36] = jj_gen;
        ;
      }
    }
    jj_consume_token(65);
  }

  static private boolean jj_2_1(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_1(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  static private boolean jj_2_2(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_2(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  static private boolean jj_2_3(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_3(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(2, xla); }
  }

  static private boolean jj_2_4(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_4(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(3, xla); }
  }

  static private boolean jj_2_5(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_5(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(4, xla); }
  }

  static private boolean jj_2_6(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_6(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(5, xla); }
  }

  static private boolean jj_2_7(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_7(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(6, xla); }
  }

  static private boolean jj_2_8(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_8(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(7, xla); }
  }

  static private boolean jj_2_9(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_9(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(8, xla); }
  }

  static private boolean jj_2_10(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_10(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(9, xla); }
  }

  static private boolean jj_2_11(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_11(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(10, xla); }
  }

  static private boolean jj_2_12(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_12(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(11, xla); }
  }

  static private boolean jj_2_13(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_13(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(12, xla); }
  }

  static private boolean jj_2_14(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_14(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(13, xla); }
  }

  static private boolean jj_2_15(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_15(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(14, xla); }
  }

  static private boolean jj_2_16(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_16(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(15, xla); }
  }

  static private boolean jj_2_17(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_17(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(16, xla); }
  }

  static private boolean jj_2_18(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_18(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(17, xla); }
  }

  static private boolean jj_2_19(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_19(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(18, xla); }
  }

  static private boolean jj_2_20(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_20(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(19, xla); }
  }

  static private boolean jj_2_21(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_21(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(20, xla); }
  }

  static private boolean jj_2_22(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_22(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(21, xla); }
  }

  static private boolean jj_2_23(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_23(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(22, xla); }
  }

  static private boolean jj_2_24(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_24(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(23, xla); }
  }

  static private boolean jj_2_25(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_25(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(24, xla); }
  }

  static private boolean jj_2_26(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_26(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(25, xla); }
  }

  static private boolean jj_2_27(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_27(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(26, xla); }
  }

  static private boolean jj_2_28(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_28(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(27, xla); }
  }

  static private boolean jj_2_29(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_29(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(28, xla); }
  }

  static private boolean jj_2_30(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_30(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(29, xla); }
  }

  static private boolean jj_2_31(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_31(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(30, xla); }
  }

  static private boolean jj_2_32(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_32(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(31, xla); }
  }

  static private boolean jj_3R_39() {
    if (jj_3R_53()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3_32()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_20() {
    if (jj_3R_21()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_12()) jj_scanpos = xsp;
    return false;
  }

  static private boolean jj_3R_75() {
    if (jj_scan_token(66)) return true;
    if (jj_3R_18()) return true;
    return false;
  }

  static private boolean jj_3R_19() {
    if (jj_3R_20()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_11()) jj_scanpos = xsp;
    return false;
  }

  static private boolean jj_3R_18() {
    if (jj_3R_19()) return true;
    return false;
  }

  static private boolean jj_3R_58() {
    if (jj_3R_38()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3_31()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_17() {
    if (jj_scan_token(IDENTIFIER)) return true;
    return false;
  }

  static private boolean jj_3R_80() {
    if (jj_scan_token(FOR)) return true;
    if (jj_scan_token(63)) return true;
    if (jj_3R_18()) return true;
    if (jj_scan_token(65)) return true;
    if (jj_3R_18()) return true;
    if (jj_scan_token(65)) return true;
    if (jj_3R_18()) return true;
    if (jj_scan_token(64)) return true;
    if (jj_3R_16()) return true;
    return false;
  }

  static private boolean jj_3R_79() {
    if (jj_scan_token(DO)) return true;
    if (jj_3R_16()) return true;
    if (jj_scan_token(WHILE)) return true;
    if (jj_scan_token(63)) return true;
    if (jj_3R_18()) return true;
    if (jj_scan_token(64)) return true;
    if (jj_scan_token(65)) return true;
    return false;
  }

  static private boolean jj_3R_49() {
    if (jj_scan_token(INTEGER_LITERAL)) return true;
    return false;
  }

  static private boolean jj_3R_38() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_49()) {
    jj_scanpos = xsp;
    if (jj_3R_50()) {
    jj_scanpos = xsp;
    if (jj_3R_51()) {
    jj_scanpos = xsp;
    if (jj_3R_52()) return true;
    }
    }
    }
    return false;
  }

  static private boolean jj_3R_78() {
    if (jj_scan_token(WHILE)) return true;
    if (jj_scan_token(63)) return true;
    if (jj_3R_18()) return true;
    if (jj_scan_token(64)) return true;
    if (jj_3R_16()) return true;
    return false;
  }

  static private boolean jj_3R_60() {
    if (jj_scan_token(108)) return true;
    if (jj_scan_token(108)) return true;
    return false;
  }

  static private boolean jj_3R_74() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_78()) {
    jj_scanpos = xsp;
    if (jj_3R_79()) {
    jj_scanpos = xsp;
    if (jj_3R_80()) return true;
    }
    }
    return false;
  }

  static private boolean jj_3_10() {
    if (jj_scan_token(ELSE)) return true;
    if (jj_3R_16()) return true;
    return false;
  }

  static private boolean jj_3R_77() {
    if (jj_scan_token(SWITCH)) return true;
    if (jj_scan_token(63)) return true;
    if (jj_3R_18()) return true;
    if (jj_scan_token(64)) return true;
    if (jj_3R_16()) return true;
    return false;
  }

  static private boolean jj_3_6() {
    if (jj_scan_token(60)) return true;
    if (jj_3R_17()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_75()) jj_scanpos = xsp;
    return false;
  }

  static private boolean jj_3_29() {
    if (jj_scan_token(INSTANCEOF)) return true;
    if (jj_3R_18()) return true;
    return false;
  }

  static private boolean jj_3_28() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(103)) {
    jj_scanpos = xsp;
    if (jj_scan_token(104)) return true;
    }
    return false;
  }

  static private boolean jj_3R_81() {
    Token xsp;
    if (jj_3_28()) return true;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3_28()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3_9() {
    if (jj_scan_token(ELSEIF)) return true;
    if (jj_scan_token(63)) return true;
    if (jj_3R_18()) return true;
    if (jj_scan_token(64)) return true;
    if (jj_3R_16()) return true;
    return false;
  }

  static private boolean jj_3R_48() {
    if (jj_3R_18()) return true;
    return false;
  }

  static private boolean jj_3R_65() {
    if (jj_scan_token(63)) return true;
    if (jj_3R_18()) return true;
    if (jj_scan_token(64)) return true;
    return false;
  }

  static private boolean jj_3R_64() {
    if (jj_3R_38()) return true;
    return false;
  }

  static private boolean jj_3R_47() {
    if (jj_3R_18()) return true;
    return false;
  }

  static private boolean jj_3R_59() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_64()) {
    jj_scanpos = xsp;
    if (jj_3R_65()) return true;
    }
    return false;
  }

  static private boolean jj_3R_45() {
    if (jj_3R_58()) return true;
    return false;
  }

  static private boolean jj_3R_76() {
    if (jj_scan_token(IF)) return true;
    if (jj_scan_token(63)) return true;
    if (jj_3R_18()) return true;
    if (jj_scan_token(64)) return true;
    if (jj_3R_16()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3_9()) { jj_scanpos = xsp; break; }
    }
    xsp = jj_scanpos;
    if (jj_3_10()) jj_scanpos = xsp;
    return false;
  }

  static private boolean jj_3R_37() {
    if (jj_scan_token(61)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_48()) jj_scanpos = xsp;
    if (jj_scan_token(62)) return true;
    return false;
  }

  static private boolean jj_3R_36() {
    if (jj_scan_token(106)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_47()) jj_scanpos = xsp;
    if (jj_scan_token(107)) return true;
    return false;
  }

  static private boolean jj_3R_35() {
    if (jj_scan_token(105)) return true;
    if (jj_3R_46()) return true;
    return false;
  }

  static private boolean jj_3R_34() {
    if (jj_scan_token(97)) return true;
    if (jj_3R_46()) return true;
    return false;
  }

  static private boolean jj_3_30() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_33()) {
    jj_scanpos = xsp;
    if (jj_3R_34()) {
    jj_scanpos = xsp;
    if (jj_3R_35()) {
    jj_scanpos = xsp;
    if (jj_3R_36()) {
    jj_scanpos = xsp;
    if (jj_3R_37()) return true;
    }
    }
    }
    }
    return false;
  }

  static private boolean jj_3R_33() {
    if (jj_scan_token(63)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_45()) jj_scanpos = xsp;
    if (jj_scan_token(64)) return true;
    return false;
  }

  static private boolean jj_3R_73() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_76()) {
    jj_scanpos = xsp;
    if (jj_3R_77()) return true;
    }
    return false;
  }

  static private boolean jj_3R_46() {
    if (jj_3R_59()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3_30()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_72() {
    if (jj_scan_token(66)) return true;
    if (jj_3R_18()) return true;
    return false;
  }

  static private boolean jj_3R_71() {
    if (jj_3R_46()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_29()) jj_scanpos = xsp;
    return false;
  }

  static private boolean jj_3R_67() {
    if (jj_3R_71()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_81()) jj_scanpos = xsp;
    return false;
  }

  static private boolean jj_3_24() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(95)) {
    jj_scanpos = xsp;
    if (jj_scan_token(96)) {
    jj_scanpos = xsp;
    if (jj_scan_token(97)) return true;
    }
    }
    if (jj_3R_31()) return true;
    return false;
  }

  static private boolean jj_3_27() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(103)) {
    jj_scanpos = xsp;
    if (jj_scan_token(104)) return true;
    }
    return false;
  }

  static private boolean jj_3_25() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(98)) {
    jj_scanpos = xsp;
    if (jj_scan_token(99)) {
    jj_scanpos = xsp;
    if (jj_scan_token(100)) return true;
    }
    }
    if (jj_3R_32()) return true;
    return false;
  }

  static private boolean jj_3R_63() {
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3_27()) { jj_scanpos = xsp; break; }
    }
    if (jj_3R_67()) return true;
    return false;
  }

  static private boolean jj_3R_70() {
    if (jj_3R_74()) return true;
    return false;
  }

  static private boolean jj_3R_69() {
    if (jj_3R_73()) return true;
    return false;
  }

  static private boolean jj_3R_62() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(84)) {
    jj_scanpos = xsp;
    if (jj_scan_token(96)) {
    jj_scanpos = xsp;
    if (jj_scan_token(101)) {
    jj_scanpos = xsp;
    if (jj_scan_token(102)) return true;
    }
    }
    }
    return false;
  }

  static private boolean jj_3_26() {
    if (jj_scan_token(63)) return true;
    if (jj_scan_token(IDENTIFIER)) return true;
    if (jj_scan_token(64)) return true;
    return false;
  }

  static private boolean jj_3_23() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(93)) {
    jj_scanpos = xsp;
    if (jj_scan_token(94)) return true;
    }
    if (jj_3R_30()) return true;
    return false;
  }

  static private boolean jj_3R_57() {
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_62()) { jj_scanpos = xsp; break; }
    }
    if (jj_3R_63()) return true;
    return false;
  }

  static private boolean jj_3R_68() {
    if (jj_3R_17()) return true;
    if (jj_scan_token(66)) return true;
    if (jj_3R_18()) return true;
    if (jj_scan_token(65)) return true;
    return false;
  }

  static private boolean jj_3_8() {
    if (jj_3R_17()) return true;
    if (jj_3R_17()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_72()) jj_scanpos = xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3_6()) { jj_scanpos = xsp; break; }
    }
    if (jj_scan_token(65)) return true;
    return false;
  }

  static private boolean jj_3R_52() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(97)) jj_scanpos = xsp;
    if (jj_scan_token(IDENTIFIER)) return true;
    return false;
  }

  static private boolean jj_3R_56() {
    if (jj_scan_token(63)) return true;
    if (jj_scan_token(IDENTIFIER)) return true;
    if (jj_scan_token(64)) return true;
    return false;
  }

  static private boolean jj_3_22() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(89)) {
    jj_scanpos = xsp;
    if (jj_scan_token(90)) {
    jj_scanpos = xsp;
    if (jj_scan_token(91)) {
    jj_scanpos = xsp;
    if (jj_scan_token(92)) return true;
    }
    }
    }
    if (jj_3R_29()) return true;
    return false;
  }

  static private boolean jj_3_21() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(85)) {
    jj_scanpos = xsp;
    if (jj_scan_token(86)) {
    jj_scanpos = xsp;
    if (jj_scan_token(87)) {
    jj_scanpos = xsp;
    if (jj_scan_token(88)) return true;
    }
    }
    }
    if (jj_3R_28()) return true;
    return false;
  }

  static private boolean jj_3R_44() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_56()) jj_scanpos = xsp;
    if (jj_3R_57()) return true;
    return false;
  }

  static private boolean jj_3R_61() {
    if (jj_3R_66()) return true;
    return false;
  }

  static private boolean jj_3_20() {
    if (jj_scan_token(84)) return true;
    if (jj_3R_27()) return true;
    return false;
  }

  static private boolean jj_3R_32() {
    if (jj_3R_44()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_25()) jj_scanpos = xsp;
    return false;
  }

  static private boolean jj_3_7() {
    if (jj_3R_18()) return true;
    if (jj_scan_token(65)) return true;
    return false;
  }

  static private boolean jj_3R_66() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_7()) {
    jj_scanpos = xsp;
    if (jj_3_8()) {
    jj_scanpos = xsp;
    if (jj_3R_68()) {
    jj_scanpos = xsp;
    if (jj_3R_69()) {
    jj_scanpos = xsp;
    if (jj_3R_70()) return true;
    }
    }
    }
    }
    return false;
  }

  static private boolean jj_3_19() {
    if (jj_scan_token(83)) return true;
    if (jj_3R_26()) return true;
    return false;
  }

  static private boolean jj_3R_16() {
    if (jj_scan_token(61)) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_61()) { jj_scanpos = xsp; break; }
    }
    if (jj_scan_token(62)) return true;
    return false;
  }

  static private boolean jj_3R_31() {
    if (jj_3R_32()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_24()) jj_scanpos = xsp;
    return false;
  }

  static private boolean jj_3R_54() {
    if (jj_3R_18()) return true;
    return false;
  }

  static private boolean jj_3_18() {
    if (jj_scan_token(82)) return true;
    if (jj_3R_25()) return true;
    return false;
  }

  static private boolean jj_3R_51() {
    if (jj_3R_60()) return true;
    return false;
  }

  static private boolean jj_3R_30() {
    if (jj_3R_31()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_23()) jj_scanpos = xsp;
    return false;
  }

  static private boolean jj_3_17() {
    if (jj_scan_token(81)) return true;
    if (jj_3R_24()) return true;
    return false;
  }

  static private boolean jj_3R_29() {
    if (jj_3R_30()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_22()) jj_scanpos = xsp;
    return false;
  }

  static private boolean jj_3_16() {
    if (jj_scan_token(80)) return true;
    if (jj_3R_23()) return true;
    return false;
  }

  static private boolean jj_3R_28() {
    if (jj_3R_29()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_21()) jj_scanpos = xsp;
    return false;
  }

  static private boolean jj_3R_41() {
    if (jj_scan_token(60)) return true;
    if (jj_scan_token(IDENTIFIER)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_54()) jj_scanpos = xsp;
    return false;
  }

  static private boolean jj_3_5() {
    if (jj_scan_token(IDENTIFIER)) return true;
    if (jj_3R_16()) return true;
    return false;
  }

  static private boolean jj_3R_27() {
    if (jj_3R_28()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_20()) jj_scanpos = xsp;
    return false;
  }

  static private boolean jj_3_15() {
    if (jj_scan_token(78)) return true;
    if (jj_3R_18()) return true;
    if (jj_scan_token(79)) return true;
    if (jj_3R_18()) return true;
    return false;
  }

  static private boolean jj_3R_26() {
    if (jj_3R_27()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_19()) jj_scanpos = xsp;
    return false;
  }

  static private boolean jj_3R_42() {
    if (jj_scan_token(IDENTIFIER)) return true;
    if (jj_scan_token(IDENTIFIER)) return true;
    if (jj_scan_token(63)) return true;
    if (jj_3R_39()) return true;
    if (jj_scan_token(64)) return true;
    if (jj_3R_16()) return true;
    return false;
  }

  static private boolean jj_3_4() {
    if (jj_scan_token(IDENTIFIER)) return true;
    if (jj_scan_token(63)) return true;
    if (jj_3R_39()) return true;
    if (jj_scan_token(64)) return true;
    if (jj_3R_16()) return true;
    return false;
  }

  static private boolean jj_3R_25() {
    if (jj_3R_26()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_18()) jj_scanpos = xsp;
    return false;
  }

  static private boolean jj_3R_40() {
    if (jj_3R_18()) return true;
    return false;
  }

  static private boolean jj_3_3() {
    if (jj_3R_15()) return true;
    return false;
  }

  static private boolean jj_3_14() {
    if (jj_3R_22()) return true;
    if (jj_3R_18()) return true;
    return false;
  }

  static private boolean jj_3R_15() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_4()) {
    jj_scanpos = xsp;
    if (jj_3R_42()) return true;
    }
    return false;
  }

  static private boolean jj_3R_24() {
    if (jj_3R_25()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_17()) jj_scanpos = xsp;
    return false;
  }

  static private boolean jj_3_13() {
    if (jj_scan_token(AND)) return true;
    if (jj_3R_21()) return true;
    return false;
  }

  static private boolean jj_3_12() {
    if (jj_scan_token(XOR)) return true;
    if (jj_3R_20()) return true;
    return false;
  }

  static private boolean jj_3R_23() {
    if (jj_3R_24()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_16()) jj_scanpos = xsp;
    return false;
  }

  static private boolean jj_3_11() {
    if (jj_scan_token(OR)) return true;
    if (jj_3R_19()) return true;
    return false;
  }

  static private boolean jj_3_32() {
    if (jj_scan_token(60)) return true;
    if (jj_3R_39()) return true;
    return false;
  }

  static private boolean jj_3R_55() {
    if (jj_3R_23()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_15()) jj_scanpos = xsp;
    return false;
  }

  static private boolean jj_3_2() {
    if (jj_scan_token(63)) return true;
    if (jj_scan_token(64)) return true;
    return false;
  }

  static private boolean jj_3_1() {
    if (jj_3R_14()) return true;
    return false;
  }

  static private boolean jj_3R_50() {
    if (jj_scan_token(FLOATING_POINT_LITERAL)) return true;
    return false;
  }

  static private boolean jj_3R_14() {
    if (jj_scan_token(IDENTIFIER)) return true;
    if (jj_scan_token(IDENTIFIER)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_40()) jj_scanpos = xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_41()) { jj_scanpos = xsp; break; }
    }
    if (jj_scan_token(65)) return true;
    return false;
  }

  static private boolean jj_3R_22() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(66)) {
    jj_scanpos = xsp;
    if (jj_scan_token(67)) {
    jj_scanpos = xsp;
    if (jj_scan_token(68)) {
    jj_scanpos = xsp;
    if (jj_scan_token(69)) {
    jj_scanpos = xsp;
    if (jj_scan_token(70)) {
    jj_scanpos = xsp;
    if (jj_scan_token(71)) {
    jj_scanpos = xsp;
    if (jj_scan_token(72)) {
    jj_scanpos = xsp;
    if (jj_scan_token(73)) {
    jj_scanpos = xsp;
    if (jj_scan_token(74)) {
    jj_scanpos = xsp;
    if (jj_scan_token(75)) {
    jj_scanpos = xsp;
    if (jj_scan_token(76)) {
    jj_scanpos = xsp;
    if (jj_scan_token(77)) return true;
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    return false;
  }

  static private boolean jj_3R_53() {
    if (jj_scan_token(IDENTIFIER)) return true;
    if (jj_scan_token(IDENTIFIER)) return true;
    return false;
  }

  static private boolean jj_3R_43() {
    if (jj_3R_55()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_14()) jj_scanpos = xsp;
    return false;
  }

  static private boolean jj_3R_21() {
    if (jj_3R_43()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_13()) jj_scanpos = xsp;
    return false;
  }

  static private boolean jj_3_31() {
    if (jj_scan_token(60)) return true;
    if (jj_3R_38()) return true;
    return false;
  }

  static private boolean jj_initialized_once = false;
  /** Generated Token Manager. */
  static public GuruCParserTokenManager token_source;
  static SimpleCharStream jj_input_stream;
  /** Current token. */
  static public Token token;
  /** Next token. */
  static public Token jj_nt;
  static private int jj_ntk;
  static private Token jj_scanpos, jj_lastpos;
  static private int jj_la;
  static private int jj_gen;
  static final private int[] jj_la1 = new int[37];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static private int[] jj_la1_2;
  static private int[] jj_la1_3;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
      jj_la1_init_2();
      jj_la1_init_3();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x10011000,0x0,0x0,0x10000000,0x10000000,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x11000,0x11000,0x11000,0x0,0x11000,0x0,0x11000,0x11000,0x0,0x11000,};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {0x23000000,0x2000000,0x10000000,0x1000000,0x82000000,0x82000000,0x80000000,0x2000000,0x2000000,0x2000000,0x82c00104,0x0,0x0,0x2c00104,0x100,0xc00004,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x2000000,0x82000000,0x82000000,0xa0000000,0x82000000,0x0,0x2000000,0x82000000,0x10000000,0x82000000,};
   }
   private static void jj_la1_init_2() {
      jj_la1_2 = new int[] {0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x100000,0x4,0x4,0x0,0x0,0x0,0x3ffc,0x1e00000,0x1e000000,0x60000000,0x80000000,0x0,0x100000,0x100000,0x0,0x0,0x0,0x0,0x100000,0x100000,0x0,0x0,0x0,0x0,0x100000,0x0,0x100000,};
   }
   private static void jj_la1_init_3() {
      jj_la1_3 = new int[] {0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x11e3,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x3,0x1c,0x61,0x61,0x180,0x180,0x180,0x1002,0x11e3,0x11e3,0x602,0x1002,0x2,0x1002,0x11e3,0x0,0x11e3,};
   }
  static final private JJCalls[] jj_2_rtns = new JJCalls[32];
  static private boolean jj_rescan = false;
  static private int jj_gc = 0;

  /** Constructor with InputStream. */
  public GuruCParser(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public GuruCParser(java.io.InputStream stream, String encoding) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser.  ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new GuruCParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 37; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 37; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public GuruCParser(java.io.Reader stream) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser. ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new GuruCParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 37; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  static public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 37; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public GuruCParser(GuruCParserTokenManager tm) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser. ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 37; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(GuruCParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 37; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  static private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      if (++jj_gc > 100) {
        jj_gc = 0;
        for (int i = 0; i < jj_2_rtns.length; i++) {
          JJCalls c = jj_2_rtns[i];
          while (c != null) {
            if (c.gen < jj_gen) c.first = null;
            c = c.next;
          }
        }
      }
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }

  static private final class LookaheadSuccess extends java.lang.Error { }
  static final private LookaheadSuccess jj_ls = new LookaheadSuccess();
  static private boolean jj_scan_token(int kind) {
    if (jj_scanpos == jj_lastpos) {
      jj_la--;
      if (jj_scanpos.next == null) {
        jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
      } else {
        jj_lastpos = jj_scanpos = jj_scanpos.next;
      }
    } else {
      jj_scanpos = jj_scanpos.next;
    }
    if (jj_rescan) {
      int i = 0; Token tok = token;
      while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
      if (tok != null) jj_add_error_token(kind, i);
    }
    if (jj_scanpos.kind != kind) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
    return false;
  }


/** Get the next Token. */
  static final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  static final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  static private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  static private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  static private int[] jj_expentry;
  static private int jj_kind = -1;
  static private int[] jj_lasttokens = new int[100];
  static private int jj_endpos;

  static private void jj_add_error_token(int kind, int pos) {
    if (pos >= 100) return;
    if (pos == jj_endpos + 1) {
      jj_lasttokens[jj_endpos++] = kind;
    } else if (jj_endpos != 0) {
      jj_expentry = new int[jj_endpos];
      for (int i = 0; i < jj_endpos; i++) {
        jj_expentry[i] = jj_lasttokens[i];
      }
      boolean exists = false;
      for (java.util.Iterator<?> it = jj_expentries.iterator(); it.hasNext();) {
        exists = true;
        int[] oldentry = (int[])(it.next());
        if (oldentry.length == jj_expentry.length) {
          for (int i = 0; i < jj_expentry.length; i++) {
            if (oldentry[i] != jj_expentry[i]) {
              exists = false;
              break;
            }
          }
          if (exists) break;
        }
      }
      if (!exists) jj_expentries.add(jj_expentry);
      if (pos != 0) jj_lasttokens[(jj_endpos = pos) - 1] = kind;
    }
  }

  /** Generate ParseException. */
  static public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[109];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 37; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
          if ((jj_la1_2[i] & (1<<j)) != 0) {
            la1tokens[64+j] = true;
          }
          if ((jj_la1_3[i] & (1<<j)) != 0) {
            la1tokens[96+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 109; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    jj_endpos = 0;
    jj_rescan_token();
    jj_add_error_token(0, 0);
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  static final public void enable_tracing() {
  }

  /** Disable tracing. */
  static final public void disable_tracing() {
  }

  static private void jj_rescan_token() {
    jj_rescan = true;
    for (int i = 0; i < 32; i++) {
    try {
      JJCalls p = jj_2_rtns[i];
      do {
        if (p.gen > jj_gen) {
          jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
          switch (i) {
            case 0: jj_3_1(); break;
            case 1: jj_3_2(); break;
            case 2: jj_3_3(); break;
            case 3: jj_3_4(); break;
            case 4: jj_3_5(); break;
            case 5: jj_3_6(); break;
            case 6: jj_3_7(); break;
            case 7: jj_3_8(); break;
            case 8: jj_3_9(); break;
            case 9: jj_3_10(); break;
            case 10: jj_3_11(); break;
            case 11: jj_3_12(); break;
            case 12: jj_3_13(); break;
            case 13: jj_3_14(); break;
            case 14: jj_3_15(); break;
            case 15: jj_3_16(); break;
            case 16: jj_3_17(); break;
            case 17: jj_3_18(); break;
            case 18: jj_3_19(); break;
            case 19: jj_3_20(); break;
            case 20: jj_3_21(); break;
            case 21: jj_3_22(); break;
            case 22: jj_3_23(); break;
            case 23: jj_3_24(); break;
            case 24: jj_3_25(); break;
            case 25: jj_3_26(); break;
            case 26: jj_3_27(); break;
            case 27: jj_3_28(); break;
            case 28: jj_3_29(); break;
            case 29: jj_3_30(); break;
            case 30: jj_3_31(); break;
            case 31: jj_3_32(); break;
          }
        }
        p = p.next;
      } while (p != null);
      } catch(LookaheadSuccess ls) { }
    }
    jj_rescan = false;
  }

  static private void jj_save(int index, int xla) {
    JJCalls p = jj_2_rtns[index];
    while (p.gen > jj_gen) {
      if (p.next == null) { p = p.next = new JJCalls(); break; }
      p = p.next;
    }
    p.gen = jj_gen + xla - jj_la; p.first = token; p.arg = xla;
  }

  static final class JJCalls {
    int gen;
    Token first;
    int arg;
    JJCalls next;
  }

  }
